// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function ForceQuit():Promise<void>;

export function GetSettings():Promise<api.Settings>;

export function GetSpotXSettings():Promise<api.SpotXSettings>;

export function Greet(arg1:string):Promise<string>;

export function IsBackgroundMode():Promise<boolean>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;

export function OpenDevTools():Promise<void>;

export function SetBackgroundMode(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetLyricsTheme(arg1:string):Promise<void>;

export function SetModuleEnabled(arg1:string,arg2:boolean):Promise<void>;

export function ToggleWindowVisibility():Promise<void>;

export function UnMaximize():Promise<void>;
