// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['app']['App']['Close']();
}

export function ForceQuit() {
  return window['go']['app']['App']['ForceQuit']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSpotXSettings() {
  return window['go']['app']['App']['GetSpotXSettings']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function IsBackgroundMode() {
  return window['go']['app']['App']['IsBackgroundMode']();
}

export function Maximize() {
  return window['go']['app']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['app']['App']['Minimize']();
}

export function OpenDevTools() {
  return window['go']['app']['App']['OpenDevTools']();
}

export function SetBackgroundMode(arg1) {
  return window['go']['app']['App']['SetBackgroundMode'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetLyricsTheme(arg1) {
  return window['go']['app']['App']['SetLyricsTheme'](arg1);
}

export function SetModuleEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetModuleEnabled'](arg1, arg2);
}

export function ToggleWindowVisibility() {
  return window['go']['app']['App']['ToggleWindowVisibility']();
}

export function UnMaximize() {
  return window['go']['app']['App']['UnMaximize']();
}
