// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function IsBackgroundMode():Promise<boolean>;

export function SetBackgroundMode(arg1:boolean):Promise<void>;
