// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function IsBackgroundMode() {
  return window['go']['app']['App']['IsBackgroundMode']();
}

export function SetBackgroundMode(arg1) {
  return window['go']['app']['App']['SetBackgroundMode'](arg1);
}
