// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['app']['App']['Close']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function IsBackgroundMode() {
  return window['go']['app']['App']['IsBackgroundMode']();
}

export function IsMaximized() {
  return window['go']['app']['App']['IsMaximized']();
}

export function Maximize() {
  return window['go']['app']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['app']['App']['Minimize']();
}

export function SetBackgroundMode(arg1) {
  return window['go']['app']['App']['SetBackgroundMode'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function ToggleMaximize() {
  return window['go']['app']['App']['ToggleMaximize']();
}

export function ToggleWindowVisibility() {
  return window['go']['app']['App']['ToggleWindowVisibility']();
}

export function UnMaximize() {
  return window['go']['app']['App']['UnMaximize']();
}
